export const initialDashboardConfig = {
  categories: [
    {
      id: "cspm-executive",
      name: "CSPM Executive Dashboard",
      widgets: [
        {
          id: "cloud-accounts",
          name: "Cloud Accounts",
          type: "donut-widget",
          segments: [{ percentage: 50, color: "#4285f4" }],
          items: [
            { color: "#4285f4", label: "Connected (2)" },
            { color: "#e8eaed", label: "Not Connected (2)" },
          ],
        },
        {
          id: "risk-assessment",
          name: "Cloud Account Risk Assessment",
          type: "donut-widget",
          segments: [
            { percentage: 17, color: "#ea4335" },
            { percentage: 7, color: "#fbbc04" },
            { percentage: 1, color: "#9aa0a6" },
            { percentage: 75, color: "#34a853" },
          ],
          items: [
            { color: "#ea4335", label: "Failed (1689)" },
            { color: "#fbbc04", label: "Warning (681)" },
            { color: "#9aa0a6", label: "Not available (36)" },
            { color: "#34a853", label: "Passed (7253)" },
          ],
        },
      ],
    },
    {
      id: "cwpp-dashboard",
      name: "CWPP Dashboard",
      widgets: [
        {
          id: "namespace-alerts",
          name: "Top 5 Namespace Specific Alerts",
          text: "No Graph data available!",
          type: "empty-graph",
        },
        {
          id: "workload-alerts",
          name: "Workload Alerts",
          text: "No Graph data available!",
          type: "empty-graph",
        },
      ],
    },
    {
      id: "registry-scan",
      name: "Registry Scan",
      widgets: [
        {
          id: "image-risk",
          name: "Image Risk Assessment",
          type: "risk-bar",
          total: 2,
          label: "Total Images are 2",
          bars: [
            { width: "50%", color: "#d93025" },
            { width: "50%", color: "#f9ab00" },
          ],
          legend: [
            { color: "#d93025", label: "Critical (2)" },
            { color: "#f9ab00", label: "High (2)" },
          ],
        },
        {
          id: "security-issues",
          name: "Image Security Issues",
          type: "risk-bar",
          total: 2,
          label: "Total Images",
          bars: [
            { width: "50%", color: "#d93025" },
            { width: "50%", color: "#f9ab00" },
          ],
          legend: [
            { color: "#d93025", label: "Critical (2)" },
            { color: "#f9ab00", label: "High (2)" },
          ],
        },
      ],
    },
  ],
};

export const styles = {
  dashboard: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    backgroundColor: "#f5f6fa",
    minHeight: "100vh",
    color: "#2c3e50",
  },
  dashboardHeader: {
    background: "white",
    padding: "16px 24px",
    borderBottom: "1px solid #e1e5e9",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
  },
  breadcrumb: {
    color: "#7f8c8d",
  },
  breadcrumbActive: {
    color: "#2c3e50",
    fontWeight: 500,
  },
  breadcrumbSeparator: {
    color: "#bdc3c7",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  searchInput: {
    padding: "8px 16px",
    border: "1px solid #e1e5e9",
    borderRadius: "6px",
    background: "#f8f9fa",
    width: "300px",
    fontSize: "14px",
    outline: "none",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  iconBtn: {
    background: "none",
    border: "none",
    padding: "8px",
    borderRadius: "4px",
    cursor: "pointer",
    color: "#7f8c8d",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  userAvatar: {
    background: "#3498db",
    color: "white",
    padding: "6px 12px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: 500,
  },
  dashboardContent: {
    padding: "24px",
  },
  dashboardTitle: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
  },
  mainTitle: {
    fontSize: "24px",
    fontWeight: 600,
    margin: 0,
    color: "#2c3e50",
  },
  titleActions: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  addWidgetBtn: {
    background: "white",
    border: "1px solid #e1e5e9",
    padding: "8px 12px",
    borderRadius: "4px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "14px",
    color: "#2c3e50",
  },
  addWidgetBtnSmall: {
    background: "#f8f9fa",
    border: "1px solid #dee2e6",
    padding: "4px 8px",
    borderRadius: "4px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "12px",
    color: "#2c3e50",
  },
  manageBtn: {
    background: "#3498db",
    color: "white",
    border: "none",
    padding: "8px 12px",
    borderRadius: "4px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "14px",
  },
  dashboardSection: {
    marginBottom: "32px",
  },
  sectionTitle: {
    fontSize: "18px",
    fontWeight: 600,
    margin: "0 0 16px 0",
    color: "#2c3e50",
  },
  widgetsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(400px, 1fr))",
    gap: "20px",
    marginBottom: "24px",
  },
  widget: {
    background: "white",
    borderRadius: "8px",
    border: "1px solid #e1e5e9",
    overflow: "hidden",
    position: "relative",
  },
  widgetHeader: {
    padding: "16px 20px 12px",
    borderBottom: "1px solid #f1f3f4",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  widgetTitle: {
    fontSize: "14px",
    fontWeight: 600,
    margin: 0,
    color: "#2c3e50",
  },
  widgetContent: {
    padding: "20px",
    minHeight: "120px",
    fontSize: "14px",
    lineHeight: "1.5",
    color: "#5f6368",
  },
  removeBtn: {
    position: "absolute",
    top: "8px",
    right: "8px",
    background: "#fff",
    border: "1px solid #e1e5e9",
    borderRadius: "4px",
    padding: "4px",
    cursor: "pointer",
    color: "#dc3545",
    display: "flex",
    alignItems: "center",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
};
